"""MSIT DEV workspace definition - all values inlined (no shared/common module)."""

from ._schema import (
    DataAccessEntry,
    DataPermission,
    FabricCapacity,
    FileAccessEntry,
    Identity,
    IdentityKind,
    LakehouseDefinition,
    Pipeline,
    PipelineActivity,
    ProjectMetadata,
    Schedule,
    Shortcut,
    SourceControlProvider,
    SourceControlSettings,
    SparkEnvironment,
    SparkJobDefinition,
    SparkLanguage,
    SparkLibrary,
    TableAccessEntry,
    TargetEnvironment,
    WorkspaceEnvironment,
    WorkspaceRole,
    spark_job_activity,
)

WORKSPACE = WorkspaceEnvironment(
    target=TargetEnvironment.DEV,
    workspace_prefix="fabric-cicd",
    workspace_name="",  # leave empty to resolve to "fabric-cicd-dev"
    workspace_id="67a4353f-223f-46fa-92da-3ab5a5cacfd2",
    capacity=FabricCapacity(
        capacity_id="F41BC187-38C5-4835-817C-629BD784ADD7",
    ),
    metadata=ProjectMetadata(
        owner="Core",
        team="DnA",
        tenant_id="33e01921-4d64-4f8c-a055-5bdaffd5e33d",
        project_name="fabric-cicd",
    ),
    source_control=SourceControlSettings(
        provider=SourceControlProvider.AzureDevOps,
        organization="msazure",
        project="One",
        repository="Asimov-vNext-Deployment",
        branch="main",
        directory="fabric",
    ),
    access_control=[
        Identity(
            display_name="fabric-cicd-contributors",
            object_id="cbb157e6-143f-4eb7-a9fb-688199a3b569",
            kind=IdentityKind.Group,
            workspace_role=WorkspaceRole.Contributor,
        ),
    ],
    lakehouses=[
        LakehouseDefinition(
            name="Lakehouse1",
            access_list=[
                DataAccessEntry(
                    display_name="Sikana.Tanupabrungsun",
                    email="Sikana.Tanupabrungsun@microsoft.com",
                    permission=DataPermission.ReadWrite,
                ),
            ],
            table_access=[
                TableAccessEntry(
                    display_name="Sikana.Tanupabrungsun",
                    email="Sikana.Tanupabrungsun@microsoft.com",
                    tables=["customers"],
                    permission=DataPermission.ReadWrite,
                ),
                TableAccessEntry(
                    display_name="v-vijareddy",
                    email="v-vijareddy@microsoft.com",
                    tables=["orders"],
                    permission=DataPermission.ReadWrite,
                ),
            ],
            file_access=[
                FileAccessEntry(
                    display_name="Sikana.Tanupabrungsun",
                    email="Sikana.Tanupabrungsun@microsoft.com",
                    paths=["/Files/raw/customers.csv"],
                    permission=DataPermission.ReadWrite,
                ),
                FileAccessEntry(
                    display_name="v-vijareddy",
                    email="v-vijareddy@microsoft.com",
                    paths=["/Files/raw/orders.csv"],
                    permission=DataPermission.ReadWrite,
                ),
            ],
        ),
        LakehouseDefinition(
            name="Lakehouse2",
            access_list=[
                DataAccessEntry(
                    display_name="v-vijareddy",
                    email="v-vijareddy@microsoft.com",
                    permission=DataPermission.ReadWrite,
                ),
            ],
            file_access=[
                FileAccessEntry(
                    display_name="v-vijareddy",
                    email="v-vijareddy@microsoft.com",
                    paths=["/Files/raw"],
                    permission=DataPermission.ReadWrite,
                ),
            ],
            shortcuts=[
                Shortcut(
                    name="adls_raw_events",
                    path="Files",
                    source_type="AdlsGen2",
                    source_location="https://sdndevusw3.dfs.core.windows.net",
                    source_subpath="/raw",
                    connection_id="f4f4053b-95fe-46ca-8493-7cbac2e3cfde",
                ),
            ],
        ),
        LakehouseDefinition(
            name="Lakehouse3",
            access_list=[
                DataAccessEntry(
                    display_name="UserC",
                    email="userC@domain.com",
                    permission=DataPermission.ReadWrite,
                ),
            ],
        ),
        LakehouseDefinition(
            name="Lakehouse4",
            access_list=[
                DataAccessEntry(
                    display_name="UserD",
                    email="userD@domain.com",
                    permission=DataPermission.ReadWrite,
                ),
            ],
        ),
        LakehouseDefinition(
            name="Lakehouse5",
            access_list=[
                DataAccessEntry(
                    display_name="UserE",
                    email="userE@domain.com",
                    permission=DataPermission.ReadWrite,
                ),
            ],
        ),
    ],
    spark_environments=[
        SparkEnvironment(
            name="DevSparkEnv",
            runtime_version="1.3",
            spark_properties={"spark.sql.shuffle.partitions": "200"},
            libraries=[SparkLibrary(file_name="my_utils-0.1.0-py3-none-any.whl")],
        ),
    ],
    spark_job_definitions=[
        SparkJobDefinition(
            name="MyJob",
            language=SparkLanguage.Scala,
            executable_file="onelake://Lakehouse1/Files/JobArtifacts/my_job.jar",
            local_executable_artifact="deploy_artifacts/my_job.jar",
            main_class="com.contoso.fabric.MyJobMain",
            command_line_arguments="arg1 true",
            additional_library_uris=[],
            default_lakehouse="Lakehouse1",
            environment="DevSparkEnv",
        ),
    ],
    pipelines=[
        Pipeline(
            name="MyPipeline",
            activities=[
                PipelineActivity(
                    name="Wait1",
                    type="Wait",
                    type_properties={"waitTimeInSeconds": 1},
                    policy={
                        "timeout": "0.12:00:00",
                        "retry": 0,
                        "retryIntervalInSeconds": 30,
                        "secureInput": False,
                        "secureOutput": False,
                    },
                ),
                spark_job_activity(
                    activity_name="RunMyJob",
                    sjd_name="MyJob",
                    depends_on=["Wait1"],
                    default_lakehouse="Lakehouse1",
                    additional_lakehouses=["Lakehouse2"],
                    command_line_arguments="--env DEV --batch daily",
                ),
            ],
            schedule=Schedule(
                type="Cron",
                enabled=True,
                interval=1,
                interval_unit="Minutes",
                start="2026-05-27T16:04:08",
                end="2026-12-31T23:59:59",
                timezone="UTC",
            ),
            schedules=[
                Schedule(
                    type="Cron",
                    enabled=True,
                    interval=15,
                    interval_unit="Minutes",
                    start="2026-06-03T11:00:00",
                    end="2027-06-03T11:00:00",
                    timezone="Eastern Standard Time",
                ),
                Schedule(
                    type="Daily",
                    enabled=True,
                    times=["11:00"],
                    start="2026-06-03T11:00:00",
                    end="2027-06-03T11:00:00",
                    timezone="Eastern Standard Time",
                ),
            ],
        ),
    ],
    api_base="https://api.fabric.microsoft.com/v1",
    realm_mode=False,
    realm_id="",
)
