name: Bug Report
description: Report a bug
title: "Bug Report"
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for reporting a bug! Please provide as much detail as possible to help us understand and reproduce the issue.
              
              **Note for GitHub Copilot users**: The more context you provide, the better we can assist you with troubleshooting and solutions.

    - type: input
      id: library-version
      attributes:
          label: Library Version
          description: What version of fabric-cicd are you using? (e.g., 1.0.0 or latest)
          placeholder: "1.0.0"
      validations:
          required: true

    - type: dropdown
      id: environment-type
      attributes:
          label: Environment Type
          description: What type of environment are you deploying to?
          options:
              - Development
              - Testing/Staging
              - Production
              - Other
      validations:
          required: true

    - type: input
      id: python-version
      attributes:
          label: Python Version
          description: What Python version are you using?
          placeholder: "3.11.0"
      validations:
          required: true

    - type: input
      id: operating-system
      attributes:
          label: Operating System
          description: What operating system are you running on?
          placeholder: "Windows 11, macOS 14, Ubuntu 22.04, etc."
      validations:
          required: true

    - type: checkboxes
      id: affected-item-types
      attributes:
          label: Affected Item Types
          description: Which Microsoft Fabric item types are affected by this bug? Select all that apply.
          options:
              - label: Notebook
              - label: Lakehouse
              - label: Data Pipeline
              - label: Dataflow
              - label: Environment
              - label: Semantic Model
              - label: Report
              - label: Warehouse
              - label: KQL Database
              - label: KQL Queryset
              - label: Eventhouse
              - label: Eventstream
              - label: Activator/Reflex
              - label: Variable Library
              - label: Mirrored Database
              - label: Real-Time Dashboard
              - label: Copy Job
              - label: Other/Unknown

    - type: dropdown
      id: authentication-method
      attributes:
          label: Authentication Method
          description: How are you authenticating with Microsoft Fabric?
          options:
              - Interactive (DefaultAzureCredential)
              - Service Principal (ClientSecretCredential)
              - Managed Identity
              - Other
      validations:
          required: true

    - type: dropdown
      id: using-parameterization
      attributes:
          label: Using Parameterization
          description: Are you using a parameter.yml file for environment-specific configurations?
          options:
              - "Yes"
              - "No"
              - "Not sure"
      validations:
          required: true

    - type: textarea
      id: problem-description
      attributes:
          label: Problem Description
          description: |
              Clearly describe the bug you encountered. Include:
              - What you were trying to do
              - What you expected to happen
              - What actually happened
          placeholder: |
              I was trying to deploy a Notebook to my Fabric workspace...
              Expected: The notebook should deploy successfully
              Actual: Deployment failed with an error
      validations:
          required: true

    - type: textarea
      id: reproduction-steps
      attributes:
          label: Steps to Reproduce
          description: |
              Provide detailed steps to reproduce the issue. Include code samples if possible.
              **Please remove any sensitive information like workspace IDs, connection strings, etc.**
          placeholder: |
              1. Create a FabricWorkspace object with these parameters...
              2. Call publish_all_items()...
              3. See error...
              
              ```python
              from fabric_cicd import FabricWorkspace
              workspace = FabricWorkspace(
                  workspace_id="your-workspace-id",
                  # ... other parameters
              )
              ```
      validations:
          required: true

    - type: textarea
      id: error-output
      attributes:
          label: Error Output
          description: |
              Please provide the complete error message and stack trace.
              For long outputs, consider using a GitHub Gist and linking it here.
          placeholder: |
              ```
              Traceback (most recent call last):
                File "...", line ..., in ...
                ...
              Error message here
              ```
      validations:
          required: false

    - type: textarea
      id: code-sample
      attributes:
          label: Code Sample
          description: |
              Provide a minimal code sample that reproduces the issue.
              **Please sanitize any sensitive information before sharing.**
          placeholder: |
              ```python
              # Your code here
              ```
      validations:
          required: false

    - type: textarea
      id: workspace-config
      attributes:
          label: Workspace Configuration
          description: |
              Provide relevant details about your Fabric workspace setup (region, capacity type, etc.)
              **Do not include sensitive information like workspace IDs or connection strings.**
          placeholder: |
              - Region: East US
              - Capacity Type: Premium
              - Item count: ~50 notebooks
              - Using custom spark pools: Yes/No
      validations:
          required: false

    - type: textarea
      id: parameter-file-sample
      attributes:
          label: Parameter File Sample (if applicable)
          description: |
              If you're using parameterization, provide a sanitized sample of your parameter.yml file.
              **Remove all sensitive values like GUIDs, connection strings, etc.**
          placeholder: |
              ```yaml
              find_replace:
                - find_value: "original-value"
                  replace_value:
                    DEV: "dev-value"
                    PROD: "prod-value"
              ```
      validations:
          required: false

    - type: textarea
      id: workaround
      attributes:
          label: Workaround
          description: Have you found any workaround for this issue?
      validations:
          required: false

    - type: textarea
      id: solution-description
      attributes:
          label: Ideal Solution
          description: Describe what you think the ideal solution should be, if you have suggestions.
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: |
              Add any other relevant details that might help diagnose the issue:
              - Screenshots
              - Fabric workspace logs
              - Related GitHub issues
              - Timeline/urgency information
              
              For large files or logs, please use https://gist.github.com/ and link here.
      validations:
          required: false
