name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: Thanks for reporting a bug!

    - type: input
      id: steps-to-reproduce
      attributes:
          label: Steps to Reproduce
          description: What are the steps to reproduce this bug?
          placeholder: |
              1. In this environment...
              1. With this config...
              1. Run '...'
              1. See error...
      validations:
          required: true

    - type: textarea
      id: what-happens
      attributes:
          label: What happens?
          description: Describe what happens when you follow the steps.
      validations:
          required: true

    - type: textarea
      id: expected-behavior
      attributes:
          label: What were you expecting to happen?
          description: Describe what you expected to happen instead.
      validations:
          required: true

    - type: textarea
      id: logs
      attributes:
          label: Any logs, error output, etc?
          description: If it is long, please paste to https://gist.github.com/ and insert the link here.  Ensure to strip any non public information.
      validations:
          required: false

    - type: input
      id: operating-system
      attributes:
          label: Operating System
          description: What operating system are you using?
      validations:
          required: true

    - type: input
      id: library-version
      attributes:
          label: Library Version
          description: What version of the library are you using?
      validations:
          required: true

    - type: input
      id: authentication-type
      attributes:
          label: Authentication Type
          description: What authentication type were you using?
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context or screenshots here.
      validations:
          required: false
