name: Bug Report
description: Report a bug
title: "Bug Report"
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: Thanks for reporting a bug!

    - type: input
      id: library-version
      attributes:
          label: Library Version
          description: What is the library version?
      validations:
          required: true

    - type: textarea
      id: problem-description
      attributes:
          label: What is the problem?
          description: Describe what the gap is and how to reproduce it.
      validations:
          required: true

    - type: textarea
      id: solution-description
      attributes:
          label: Is there an ideal solution?
          description: Describe the ideal solution if there is one.
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context, screenshots, logs, error output, etc
          description: Add any other relevant details. If it is long, please paste to https://gist.github.com/ and insert the link here.  Ensure to strip any non public information.
      validations:
          required: false
