name: Bug Report
description: Report a bug
title: "Bug Report"
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: Thanks for reporting a bug!

    - type: checkboxes
      id: reproducible
      attributes:
          label: Please confirm the following
          options:
              - label: The bug is consistently reproducible
              - label: Debug logs were captured with `change_log_level()`

    - type: textarea
      id: what-happens
      attributes:
          label: What happens?
          description: What are the steps to reproduce this bug? Describe what happens when you follow the steps.
      validations:
          required: true

    - type: textarea
      id: expected-behavior
      attributes:
          label: What were you expecting to happen?
          description: Describe what you expected to happen instead.
      validations:
          required: true

    - type: dropdown
      id: operating-system
      attributes:
          label: Operating System
          description: What operating system are you using?
          options:
              - Windows
              - Mac/Linux
      validations:
          required: true

    - type: input
      id: library-version
      attributes:
          label: Library Version
          description: What version of the library are you using?
      validations:
          required: true

    - type: dropdown
      id: authentication-type
      attributes:
          label: Authentication Type
          description: What authentication type were you using?
          options:
              - User Identity
              - System Identity (SPN, MI, Etc)
              - Other
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context, screenshots, logs, error output, etc
          description: Add any other relevant details. If it is long, please paste to https://gist.github.com/ and insert the link here.  Ensure to strip any non public information.
      validations:
          required: false
