name: Feature Request
description: Request a feature
title: "Feature Request"
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: Thanks for suggesting a feature!

    - type: textarea
      id: problem-description
      attributes:
          label: What is the feature?
          description: Describe what the gap is and the ideal solution.
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context or screenshots here.
      validations:
          required: false
