name: "🚀 Feature Request"
description: Request a feature
title: "[FEATURE]"
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand and evaluate your request.

    - type: textarea
      id: problem-description
      attributes:
          label: What is the feature?
          description: Describe what the gap is and the ideal solution.
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context or screenshots here.
      validations:
          required: false
