name: Documentation Feedback
description: Provide documentation feedback
title: "Documentation Feedback"
labels: ["documentation"]
body:
    - type: markdown
      attributes:
          value: Thanks for providing documentation feedback!

    - type: input
      id: documentation-location
      attributes:
          label: URL to documentation
          description: Provide a URL to the documentation location.
      validations:
          required: true

    - type: textarea
      id: feedback
      attributes:
          label: Feedback
          description: What is the feedback?
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context or screenshots here.
      validations:
          required: false
