name: Question
description: Ask a question
title: "Question"
labels: ["question"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for asking a question! We're here to help you succeed with fabric-cicd.
              
              **Quick Start**: Only your question and goal are required to get started.

    - type: textarea
      id: the-question
      attributes:
          label: Your Question
          description: |
              What do you need help with? Be as specific as possible.
          placeholder: |
              How do I...?
              What's the best way to...?
              Is it possible to...?
              I'm getting an error when...
      validations:
          required: true

    - type: textarea
      id: trying-to-achieve
      attributes:
          label: What are you trying to achieve?
          description: |
              Describe what you're trying to accomplish and why.
          placeholder: |
              I'm trying to...
              The goal is to...
              I need to accomplish this because...
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context (Optional)
          description: |
              Help us understand your situation better:
          placeholder: |
              Experience level: New/Familiar/Experienced with fabric-cicd and Microsoft Fabric
              Question category: Getting Started/Authentication/Deployment/etc.
              Related item types: Notebooks, Data Pipelines, etc.
              What I've tried: ...
              Environment details: fabric-cicd version, Python version, OS, etc.
              Code sample: (please remove sensitive information)
              Expected outcome: ...
              Urgency: Low/Medium/High
              Research done: Documentation read, examples tried, etc.
      validations:
          required: false
