name: Question
description: Ask a question
title: "Question"
labels: ["question"]
body:
    - type: markdown
      attributes:
          value: Thanks for asking a question!

    - type: textarea
      id: trying-to-achieve
      attributes:
          label: What is the question?
          description: Clearly state the question.
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context or screenshots here.
      validations:
          required: false
