name: Technical Debt
description: Raises technical debt
title: "Technical Debt"
labels: ["tech debt"]
body:
    - type: markdown
      attributes:
          value: Used internally to raise improvements in code quality, maintainability, and technical debt.

    - type: textarea
      id: problem-description
      attributes:
          label: What is the problem?
          description: Describe what the gap is and how to reproduce it.
      validations:
          required: true

    - type: textarea
      id: solution-description
      attributes:
          label: Is there an ideal solution?
          description: Describe the ideal solution if there is one.
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context or screenshots here.
      validations:
          required: false
