name: Github Pages
# Once we release to pypi, this instead will be moved to DevOps as part of release
on:
    workflow_dispatch:

permissions:
    contents: write
    actions: write

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.9"

            - name: Install Requirements
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install uv

            - name: Deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config user.name github-actions[bot]
                  git config user.email github-actions[bot]@users.noreply.github.com
                  git fetch --no-tags --prune --depth=1 origin +refs/heads/gh-pages:refs/remotes/origin/gh-pages
                  uv sync
                  VERSION=$(grep -oP '(?<=^VERSION = ").*(?=")' src/fabric_cicd/constants.py)
                  uv run mike deploy \
                    --update-aliases \
                    --branch gh-pages \
                    --push \
                    $VERSION \
                    latest
                  uv run mike set-default --push latest
