# Workflow inspiration and adaptation came from Andruino-Cli
# https://github.com/squidfunk/mkdocs-material/discussions/6546
name: Github Pages
on:
  push:
    branches:
      - users/JacobKnightley/documentation

  create:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-doc.txt

      - name: Deploy
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git fetch --no-tags --prune --depth=1 origin +refs/heads/gh-pages:refs/remotes/origin/gh-pages
          mike deploy \
            --update-aliases \
            --branch gh-pages \
            --push \
            0.0.1 \
            latest
