name: Validate Version Bump

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]
        branches:
            - main

jobs:
    validate-version-bump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Fetch all branches
              run: git fetch --prune --unshallow
            - name: Enforce version bump PR rules
              id: version_bump_check
              run: |
                  set -e
                  echo ${{ github.repository }}
                  PR_TITLE="${{ github.event.pull_request.title }}"
                  VERSION_REGEX='^v([0-9]+\.[0-9]+\.[0-9]+)$'
                  BASE_REF="origin/main"
                  CHANGED_FILES=$(git diff --name-only $BASE_REF...HEAD)

                  VERSION_CHANGED=false
                  OLD_VERSION=""
                  NEW_VERSION=""
                  # Get VERSION from main branch
                  OLD_VERSION=$(git show origin/main:src/fabric_cicd/constants.py | grep '^VERSION = ' | sed -E 's/VERSION = "([^"]+)"/\1/')
                  # Get VERSION from current branch
                  NEW_VERSION=$(grep '^VERSION = ' src/fabric_cicd/constants.py | sed -E 's/VERSION = "([^"]+)"/\1/')

                  VERSION_CHANGED=false
                  if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
                    VERSION_CHANGED=true
                  fi

                  # Check if PR title matches version bump format
                  TITLE_IS_VERSION=false
                  if [[ "$PR_TITLE" =~ $VERSION_REGEX ]]; then
                    TITLE_IS_VERSION=true
                  fi

                  # 1. If version is updated, title must match
                  if [ "$VERSION_CHANGED" = true ]; then
                    EXPECTED_TITLE="v$NEW_VERSION"
                    if [ "$PR_TITLE" != "$EXPECTED_TITLE" ]; then
                      echo "::error::PR title must be vX.X.X when VERSION is changed. Expected title: $EXPECTED_TITLE"
                      exit 1
                    fi
                  fi

                  # 2. If title is version format, only constants.py and changelog.md should be changed
                  if [[ "$PR_TITLE" =~ $VERSION_REGEX ]]; then
                    EXPECTED_FILES="src/fabric_cicd/constants.py src/fabric_cicd/changelog.md"
                    SORTED_CHANGED=$(echo $CHANGED_FILES | tr ' ' '\n' | sort | tr '\n' ' ')
                    SORTED_EXPECTED=$(echo $EXPECTED_FILES | tr ' ' '\n' | sort | tr '\n' ' ')
                    if [ "$SORTED_CHANGED" != "$SORTED_EXPECTED" ]; then
                      echo "::error::Only constants.py and changelog.md are allowed to be included in a PR that is titled vX.X.X."
                      exit 1
                    fi
                  fi
