name: Validate Version Bump (Reusable)
description: "Reusable workflow to validate version bump PRs"

on:
    workflow_call:
        inputs:
            pr_title:
                description: "PR title to validate"
                required: true
                type: string
            pr_head_sha:
                description: "PR head SHA"
                required: true
                type: string
        outputs:
            is_version_bump:
                description: "Whether this is a version bump PR"
                value: ${{ jobs.validate-version-bump.outputs.is_version_bump }}

jobs:
    validate-version-bump:
        name: Validate Version Bump
        runs-on: ubuntu-latest
        outputs:
            is_version_bump: ${{ steps.version_bump_check.outputs.is_version_bump }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Validate Version Bump
              id: version_bump_check
              run: |
                  set -e
                  PR_TITLE="${{ inputs.pr_title }}"
                  VERSION_REGEX='^v([0-9]+\.[0-9]+\.[0-9]+)$'
                  BASE_REF="origin/main"
                  CHANGED_FILES=$(git diff --name-only $BASE_REF...${{ inputs.pr_head_sha }})

                  VERSION_CHANGED=false
                  TITLE_IS_VERSION=false
                  OLD_VERSION=""
                  NEW_VERSION=""
                  # Get VERSION from main branch
                  OLD_VERSION=$(git show origin/main:src/fabric_cicd/constants.py | grep '^VERSION = ' | sed -E 's/VERSION = "([^"]+)"/\1/')
                  # Get VERSION from current branch
                  NEW_VERSION=$(grep '^VERSION = ' src/fabric_cicd/constants.py | sed -E 's/VERSION = "([^"]+)"/\1/')

                  if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
                    VERSION_CHANGED=true
                  fi

                  if [[ "$PR_TITLE" =~ $VERSION_REGEX ]]; then
                    TITLE_IS_VERSION=true
                  fi

                  if [ "$TITLE_IS_VERSION" = true ] || [ "$VERSION_CHANGED" = true ]; then
                    echo "is_version_bump=true" >> $GITHUB_OUTPUT
                  else
                    echo "is_version_bump=false" >> $GITHUB_OUTPUT
                    echo "✅ Version bump validation passed."
                    exit 0
                  fi

                  # 1. If version is updated, title must match
                  if [ "$VERSION_CHANGED" = true ]; then
                    EXPECTED_TITLE="v$NEW_VERSION"
                    if [ "$PR_TITLE" != "$EXPECTED_TITLE" ]; then
                      echo "❌ PR title must be vX.X.X when VERSION is changed. Expected title: $EXPECTED_TITLE"
                      exit 1
                    fi
                  fi

                  # 2. If title is version format, only constants.py and changelog.md should be changed
                  if [[ "$PR_TITLE" =~ $VERSION_REGEX ]]; then
                    EXPECTED_FILES="src/fabric_cicd/constants.py src/fabric_cicd/changelog.md"
                    SORTED_CHANGED=$(echo $CHANGED_FILES | tr ' ' '\n' | sort | tr '\n' ' ')
                    SORTED_EXPECTED=$(echo $EXPECTED_FILES | tr ' ' '\n' | sort | tr '\n' ' ')
                    if [ "$SORTED_CHANGED" != "$SORTED_EXPECTED" ]; then
                      echo "❌ Only constants.py and changelog.md are allowed to be included in a PR that is titled vX.X.X."
                      exit 1
                    fi
                  fi
                  echo "✅ Version bump validation passed."
